3 Create the option to use own prices / self provided prices
V2G-liberty/HA-manual-install pull request #4
Opened 2024-03-26 19:12 UTC by ArdJonker

Completed the functionality to:
+ Read prices/emissions from a third party integration (e.g. Amber Electric)
+ Process these prices/emissions
+ Upload them to FlexMeasures.
+ Request a new schedule if prices/emissions have changed.

2024-03-26 21:53 UTC, Flix6x requested changes
Mostly requesting extra documentation. A potential follow-up would then be to discuss current limitations of the input entity and potential for generalization.

2024-03-26 21:53 UTC, Flix6x commented on appdaemon/apps/v2g-liberty/manage_own_price_data.py
> +            # we emissions % = 100 - renewables %.
Rationale: FlexMeasures runs a cost **minimization**.

2024-03-26 21:53 UTC, Flix6x commented on appdaemon/apps/v2g-liberty/manage_own_price_data.py
> +    There are entities for a fixed consumption- and production price for the next interval.
An (abbreviated) example of such an entity would help this docstring.

2024-03-27 11:05 UTC, ArdJonker commented on appdaemon/apps/v2g-liberty/get_fm_data.py
> +            # The max value in the list should match 95%. Expected are only positive values.
Indeed, will explain in comment

2024-03-27 11:05 UTC, ArdJonker commented on README.md
> +# The "own price configuration" is mend to be "on the way to generic" but currently
Will correct this

2024-03-27 12:03 UTC, ArdJonker commented on appdaemon/apps/v2g-liberty/manage_own_price_data.py
> +    HA_PPX_SENSOR_ID: str
Will add comments

2024-03-27 12:03 UTC, ArdJonker commented on appdaemon/apps/v2g-liberty/manage_own_price_data.py
> +    UOM_LABEL: str
These all need comments, UOM: Unit of Measure.

2024-03-27 12:20 UTC, ArdJonker commented on appdaemon/apps/v2g-liberty/manage_own_price_data.py
> +            # we emissions % = 100 - renewables %.
will add

2024-03-27 12:21 UTC, ArdJonker commented on appdaemon/apps/v2g-liberty/manage_own_price_data.py
> +    There are entities for a fixed consumption- and production price for the next interval.
will add

2024-04-02 06:15 UTC, ArdJonker commented on appdaemon/apps/v2g-liberty/get_fm_data.py
> +            # TODO: Improve
Removed

2024-04-02 06:22 UTC, merged